version: '3.7'

services:
  flyway:
    image: flyway/flyway:6.3.1
    command: -url=jdbc:postgresql://postgres:5432/db-hackathon -schemas=financial -user=hackathon -password=secret -locations=filesystem:/common,/dev -connectRetries=60 migrate
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=hackathon
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=db-hackathon