version: '3.7'

services:
  flyway:
    image: flyway/flyway:6.3.1
    command: -configFiles=/flyway/conf/flyway.config -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - ${PWD}/sql_versions:/flyway/sql
      - ${PWD}/docker-flyway.config:/flyway/conf/flyway.config
    depends_on:
      - postgres

  postgres:
    image: postgres:9.6
    restart: always
    ports:
    - "5432:5432"
    environment:
    - POSTGRES_USER=hackathon
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=db-hackathon